# Generated by Django 5.2.1 on 2025-06-01 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('Personnel_number', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')], verbose_name='شماره پرسنلی')),
                ('National_ID', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('email', models.EmailField(blank=True, help_text='اختیاری', max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=16, verbose_name='شماره همراه')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('Educational_degree', models.CharField(choices=[('d', 'دیپلم'), ('a', 'کارشناسی ناپیوسته'), ('b', 'کارشناسی'), ('m', 'کارشناسی ارشد'), ('p', 'دکتری'), ('o', 'سایر')], max_length=10, verbose_name='مدرک تحصیلی')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور')),
            ],
            options={
                'verbose_name': 'دارنده حساب',
                'verbose_name_plural': 'دارندگان حساب',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('mission_location', models.CharField(max_length=100, verbose_name='محل(مقصد) ماموریت')),
                ('mission_origin', models.CharField(max_length=100, verbose_name='مبدا ماموریت')),
                ('Mission_Description', models.TextField(verbose_name='توضیحات ماموریت')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PersonalInfo', models.ManyToManyField(related_name='missions', to='holder.personalinfo')),
            ],
            options={
                'verbose_name': 'ماموریت',
                'verbose_name_plural': 'ماموریت ها',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technical_items', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کالا')),
                ('type_Item', models.CharField(choices=[('Technical', 'فنی'), ('Non-technical', 'غیر فنی')], max_length=50, verbose_name='نوع کالا')),
                ('Delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره سریال')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد محصول')),
                ('PersonalInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='holder.personalinfo')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=100, verbose_name='نام مدرک')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('Training_hours', models.IntegerField(verbose_name='ساعت آموزشی')),
                ('Training_costs', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='(ریال)هزینه آموزشی')),
                ('Training_location', models.CharField(max_length=100, verbose_name='محل آموزشی')),
                ('Type_of_training', models.CharField(choices=[('online', 'اینترنتی'), ('offline', 'حضوری')], max_length=50, verbose_name='نوع آموزش')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PersonalInfo', models.ManyToManyField(related_name='documents', to='holder.personalinfo')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_submission', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل')),
                ('Internal_meetings', models.IntegerField(verbose_name='جلسات داخلی')),
                ('Meeting_Minutes', models.TextField(verbose_name='صورت جلسات')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PersonalInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='holder.personalinfo')),
            ],
            options={
                'verbose_name': 'نتیجه',
                'verbose_name_plural': 'نتایج',
            },
        ),
    ]
