# Generated by Django 5.2.1 on 2025-06-01 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='date_created',
            new_name='register_date',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Delivery_date',
        ),
        migrations.AddField(
            model_name='items',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
