# Generated by Django 5.2.1 on 2025-06-01 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_rename_date_created_items_register_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ اقدام')),
                ('action_type', models.CharField(choices=[('assign', 'تخصیص'), ('transfer', 'انتقال'), ('return', 'بازگشت'), ('maintenance', 'تعمیر'), ('other', 'سایر')], max_length=20, verbose_name='نوع اقدام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_items_history', to='holder.personalinfo', verbose_name='از شخص')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='holder.items', verbose_name='کالا')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_items_history', to='holder.personalinfo', verbose_name='به شخص')),
            ],
            options={
                'verbose_name': 'تاریخچه کالا',
                'verbose_name_plural': 'تاریخچه کالاها',
                'ordering': ['-action_date'],
            },
        ),
    ]
