# Generated by Django 5.2.1 on 2025-06-01 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0003_itemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='PersonalInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='holder.personalinfo', verbose_name='دارنده حساب'),
        ),
        migrations.AlterField(
            model_name='items',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.CreateModel(
            name='PendingItemChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('transfer', 'انتقال کالا'), ('edit', 'ویرایش کالا'), ('delete', 'حذف کالا')], max_length=20, verbose_name='نوع تغییر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('admin_description', models.TextField(verbose_name='توضیحات ادمین')),
                ('user_response', models.TextField(blank=True, null=True, verbose_name='پاسخ کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('affected_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_notifications', to='holder.personalinfo', verbose_name='فرد متاثر')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='holder.items', verbose_name='کالا')),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_item_changes', to='holder.personalinfo', verbose_name='مالک جدید')),
            ],
            options={
                'verbose_name': 'تغییر در انتظار تایید',
                'verbose_name_plural': 'تغییرات در انتظار تایید',
                'ordering': ['-created_at'],
            },
        ),
    ]
