# Generated by Django 5.2.1 on 2025-06-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0004_alter_items_personalinfo_alter_items_update_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingItemChange',
        ),
    ]
