# Generated by Django 5.2.1 on 2025-06-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0005_delete_pendingitemchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingItemChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('transfer', 'انتقال')], max_length=20, verbose_name='نوع تغییر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('admin_message', models.TextField(blank=True, null=True, verbose_name='پیام ادمین')),
                ('user_response_message', models.TextField(blank=True, null=True, verbose_name='پاسخ کاربر')),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='holder.personalinfo', verbose_name='کاربر مرتبط')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holder.items', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'تغییر در انتظار تایید',
                'verbose_name_plural': 'تغییرات در انتظار تایید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('item_change', 'تغییر کالا'), ('system', 'سیستمی'), ('admin_message', 'پیام ادمین')], max_length=20, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='holder.personalinfo', verbose_name='کاربر')),
                ('pending_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='holder.pendingitemchange', verbose_name='تغییر مرتبط')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
