# Generated by Django 5.2.1 on 2025-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0006_pendingitemchange_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cه'},
        ),
        migrations.AlterField(
            model_name='results',
            name='Internal_meetings',
            field=models.IntegerField(verbose_name='جلسات داخلی'),
        ),
    ]
