# Generated by Django 5.2.1 on 2025-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0007_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='item',
        ),
        migrations.AlterField(
            model_name='results',
            name='Internal_meetings',
            field=models.IntegerField(verbose_name='جلسات داخلی'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PendingItemChange',
        ),
    ]
