# Generated by Django 5.2.1 on 2025-06-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0008_remove_pendingitemchange_affected_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'اضافه کردن'), ('edit', 'ویرایش'), ('delete', 'حذف'), ('transfer', 'انتقال')], max_length=20, verbose_name='نوع عملیات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه کالا')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کالا')),
                ('item_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع کالا')),
                ('item_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره سریال')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد محصول')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('admin_user', models.CharField(max_length=150, verbose_name='ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='holder.personalinfo', verbose_name='کاربر هدف')),
                ('transfer_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_notifications', to='holder.personalinfo', verbose_name='انتقال به')),
            ],
            options={
                'verbose_name': 'اعلان ادمین',
                'verbose_name_plural': 'اعلان\u200cهای ادمین',
                'ordering': ['-created_at'],
            },
        ),
    ]
