# Generated by Django 5.2.1 on 2025-06-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0009_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
