# Generated by Django 5.2.1 on 2025-06-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0010_delete_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status_item',
            field=models.CharField(choices=[('Healthy', 'سالم'), ('Repairing', 'تعمیری'), ('worn out', 'فرسوده'), ('warehouse', 'انبار'), ('other', 'سایر')], default=1, max_length=50, verbose_name='وضعیت کالا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='types_of_missions',
            field=models.CharField(default=1, max_length=100, verbose_name='نوع ماموریت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='PersonalInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='holder.personalinfo', verbose_name='دارنده حساب'),
        ),
    ]
