# Generated by Django 5.2.1 on 2025-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0011_items_status_item_mission_types_of_missions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Configuration',
            field=models.TextField(blank=True, null=True, verbose_name='پیکربندی'),
        ),
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برند'),
        ),
    ]
