# Generated by Django 5.2.1 on 2025-06-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0012_items_configuration_items_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_origin',
        ),
        migrations.AddField(
            model_name='mission',
            name='time_frame',
            field=models.CharField(default=1, help_text='لطفا تعداد روز ماموریت را وارد کنید', max_length=100, verbose_name='بازه زمانی ماموریت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='Mission_Description',
            field=models.TextField(verbose_name='توضیحات(موضوع) ماموریت'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='PersonalInfo',
            field=models.ManyToManyField(related_name='missions', to='holder.personalinfo', verbose_name='حاضرین در ماموریت'),
        ),
    ]
