# Generated by Django 5.2.1 on 2025-06-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0013_remove_mission_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status_item',
            field=models.CharField(choices=[('hardware', '(تعمیری)سخت افزار'), ('Delivery', 'تحویل'), ('warehouse', 'انبار')], max_length=50, verbose_name='وضعیت کالا'),
        ),
    ]
