# Generated by Django 5.2.1 on 2025-06-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0014_alter_items_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status_sub_item',
            field=models.CharField(blank=True, choices=[('repair', 'تعمیر'), ('upgrade', 'ارتقا'), ('external', 'خارج'), ('internal', 'داخل'), ('ready', 'آماده بکار'), ('returned_good', 'عودتی سالم'), ('returned_worn', 'عودتی فرسوده')], max_length=50, null=True, verbose_name='زیر مجموعه وضعیت'),
        ),
    ]
