# Generated by Django 5.2.1 on 2025-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0015_items_status_sub_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد کالا'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Product_code',
            field=models.CharField(default=1, max_length=100, verbose_name='کد محصول'),
            preserve_default=False,
        ),
    ]
