# Generated by Django 5.2.1 on 2025-07-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0016_items_number_alter_items_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingItemChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('update', 'بروزرسانی'), ('transfer', 'انتقال'), ('status_change', 'تغییر وضعیت'), ('delete', 'حذف')], max_length=20, verbose_name='نوع تغییر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('old_data', models.JSONField(help_text='داده\u200cهای کالا قبل از تغییر', verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(help_text='داده\u200cهای پیشنهادی برای تغییر', verbose_name='داده\u200cهای جدید')),
                ('requested_by', models.CharField(help_text='نام کاربر مدیر که تغییر را درخواست کرده', max_length=100, verbose_name='درخواست\u200cدهنده')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('request_reason', models.TextField(blank=True, null=True, verbose_name='دلیل تغییر')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='نظر دارنده حساب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='holder.items', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'تغییر در انتظار تایید',
                'verbose_name_plural': 'تغییرات در انتظار تایید',
                'ordering': ['-request_date'],
            },
        ),
    ]
