# Generated by Django 5.2.1 on 2025-07-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0017_pendingitemchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingitemchange',
            options={'ordering': ['-created_at'], 'verbose_name': 'تغییر در انتظار تایید', 'verbose_name_plural': 'تغییرات در انتظار تایید'},
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='request_reason',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='pendingitemchange',
            name='reviewed_date',
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='action_type',
            field=models.CharField(choices=[('assign', 'تخصیص کالا'), ('remove', 'حذف کالا'), ('transfer', 'انتقال کالا'), ('update', 'بروزرسانی کالا')], default='update', max_length=20, verbose_name='نوع تغییر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید/رد'),
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت تایید'),
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='approval_required_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='changes_to_approve', to='holder.personalinfo', verbose_name='تایید کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00', verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_pending_changes', to='holder.personalinfo', verbose_name='دارنده فعلی'),
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='description',
            field=models.TextField(default='توضیحات', verbose_name='شرح تغییر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='new_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_pending_changes', to='holder.personalinfo', verbose_name='دارنده جدید'),
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='new_item_data',
            field=models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید کالا'),
        ),
        migrations.AddField(
            model_name='pendingitemchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='items',
            name='status_item',
            field=models.CharField(choices=[('hardware', 'سخت افزار'), ('Delivery', 'تحویل'), ('warehouse', 'انبار')], max_length=50, verbose_name='وضعیت کالا'),
        ),
        migrations.AlterField(
            model_name='pendingitemchange',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to='holder.personalinfo', verbose_name='درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='pendingitemchange',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=15, verbose_name='وضعیت'),
        ),
    ]
