# Generated by Django 5.2.1 on 2025-07-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0018_alter_pendingitemchange_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingItemChange',
        ),
    ]
