# Generated by Django 5.2.1 on 2025-07-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0019_delete_pendingitemchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=100, verbose_name='درخواست کننده')),
                ('change_type', models.CharField(choices=[('edit', 'ویرایش کالا'), ('transfer', 'انتقال کالا'), ('delete', 'حذف کالا'), ('status_change', 'تغییر وضعیت')], max_length=20, verbose_name='نوع تغییر')),
                ('description', models.TextField(verbose_name='توضیحات تغییر')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='پیام پاسخ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='holder.items', verbose_name='کالا')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_change_requests', to='holder.personalinfo', verbose_name='مالک کالا')),
            ],
            options={
                'verbose_name': 'درخواست تغییر کالا',
                'verbose_name_plural': 'درخواست\u200cهای تغییر کالا',
                'ordering': ['-created_at'],
            },
        ),
    ]
