# Generated by Django 5.2.1 on 2025-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0020_itemchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchangerequest',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='itemchangerequest',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='itemchangerequest',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='itemchangerequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='itemchangerequest',
            name='response_message',
        ),
        migrations.AddField(
            model_name='itemchangerequest',
            name='action_type',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('transfer', 'انتقال'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت')], default=1, max_length=20, verbose_name='نوع تغییر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemchangerequest',
            name='admin_user',
            field=models.CharField(default=1, max_length=150, verbose_name='کاربر مدیر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemchangerequest',
            name='proposed_changes',
            field=models.JSONField(default=1, help_text='تغییرات پیشنهادی در قالب JSON', verbose_name='تغییرات پیشنهادی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemchangerequest',
            name='description',
            field=models.TextField(help_text='توضیحات مربوط به تغییر', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='itemchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
