# Generated by Django 5.2.1 on 2025-07-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0021_remove_itemchangerequest_change_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='admin_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کاربر مدیر'),
        ),
        migrations.AlterField(
            model_name='itemchangerequest',
            name='action_type',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('transfer', 'انتقال'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت'), ('excel_update', 'ورودی Excel')], max_length=20, verbose_name='نوع تغییر'),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='action_type',
            field=models.CharField(choices=[('assign', 'تخصیص'), ('transfer', 'انتقال'), ('return', 'بازگشت'), ('maintenance', 'تعمیر'), ('edit', 'ویرایش'), ('excel_import', 'ورودی Excel'), ('other', 'سایر')], max_length=20, verbose_name='نوع اقدام'),
        ),
    ]
