# Generated by Django 5.2.1 on 2025-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0022_itemhistory_admin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='admin_user',
        ),
        migrations.AlterField(
            model_name='itemchangerequest',
            name='action_type',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('transfer', 'انتقال'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت')], max_length=20, verbose_name='نوع تغییر'),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='action_type',
            field=models.CharField(choices=[('assign', 'تخصیص'), ('transfer', 'انتقال'), ('return', 'بازگشت'), ('maintenance', 'تعمیر'), ('other', 'سایر')], max_length=20, verbose_name='نوع اقدام'),
        ),
    ]
