# Generated by Django 5.2.1 on 2025-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0023_remove_itemhistory_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='admin_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کاربر مدیر'),
        ),
    ]
