# Generated by Django 5.2.1 on 2025-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0024_itemhistory_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='admin_user',
        ),
        migrations.AlterField(
            model_name='itemchangerequest',
            name='action_type',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('transfer', 'انتقال'), ('assign', 'تخصیص'), ('remove', 'حذف'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت')], max_length=20, verbose_name='نوع تغییر'),
        ),
    ]
