# Generated by Django 5.2.1 on 2025-08-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0025_add_new_action_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchangerequest',
            name='action_type',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('transfer', 'انتقال'), ('receive', 'دریافت'), ('assign', 'تخصیص'), ('remove', 'حذف'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت')], max_length=20, verbose_name='نوع تغییر'),
        ),
    ]
