# Generated by Django 5.2.1 on 2025-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0026_alter_itemchangerequest_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Number',
        ),
        migrations.AlterField(
            model_name='items',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره سریال'),
        ),
    ]
