# Generated by Django 5.2.1 on 2025-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0027_remove_items_number_alter_items_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد کالا'),
        ),
    ]
